name: Publish website
on:
  schedule:
    - cron: '0 8 * * *' # Every day at 8a UTC
  workflow_dispatch:
    inputs:
      gatherData:
        description: "Gather data"
        required: false
        default: true
        type: boolean
      processData:
        description: "Process data"
        required: false
        default: true
        type: boolean
      publishData:
        description: "Publish data to website"
        required: false
        default: true
        type: boolean

jobs:
  Publish:
    name: Publish
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: python_code

      - name: Setup python
        if: ${{ (github.event_name == 'workflow_dispatch' && (inputs.gatherData || inputs.processData)) || github.event_name == 'schedule' }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.2"
          cache: "pip"

      - name: Install dependencies
        if: ${{ (github.event_name == 'workflow_dispatch' && (inputs.gatherData || inputs.processData)) || github.event_name == 'schedule' }}
        run: |
          python -m pip install --upgrade pip
          pip install -r python_code/requirements.txt

      - name: Run get_universal_data.py
        if: ${{ (github.event_name == 'workflow_dispatch' && inputs.gatherData) || github.event_name == 'schedule' }}
        run: |
          cd python_code
          python3 get_universal_data.py

      - name: Run process_universal_data.py
        if: ${{ (github.event_name == 'workflow_dispatch' && inputs.processData) || github.event_name == 'schedule' }}
        run: |
          cd python_code
          python3 process_universal_data.py

      - name: Update repo
        if: ${{ (github.event_name == 'workflow_dispatch' && inputs.publishData) || github.event_name == 'schedule' }}
        run: |
          cd python_code
          git config user.name "github-actions"
          git config user.email "github-actions@fake.com"
          git remote set-url origin https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/anderpups/universal_hotel_scraper.git
          git add .
          git commit -m "Update data" --allow-empty
          git push --verbose

      - name: Publish website
        if: ${{ (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' && inputs.publishData) || github.event_name == 'schedule' }}
        run: |
          git clone https://github.com/anderpups/anderpups.github.io.git
          cd anderpups.github.io      
          cp -fv ../python_code/data/* ./
          git config user.name "github-actions"
          git config user.email "github-actions@fake.com"
          git remote set-url origin https://github-actions:${{ secrets.ANDERPUPS_GITHUB_IO_PAT }}@github.com/anderpups/anderpups.github.io.git
          git add .
          git commit -m "Update website" --allow-empty
          git push --verbose
